analytics:
  google:
    id: UA-106049489-1
  piwik:
    site_id: 1
    api:
      url: http://analytics.iwuzhen.org/?callback=?
      token: 15d9071c7f8798dea950f579b2d8896e

repository: ider-zh/BYR-Navi
repository_url: https://github.com/ider-zh/BYR-Navi

timezone: Asia/Shanghai
lang: zh_CN

name: Lambdax导航 · LMD-Navi
alias: Lambdax导航
author: ider
# author_url: http://irockbunny.com
organization: LMD
organization_url: http://lambdax.cn
description: A Navigation Website for LMD
keywords: Lambdax导航,  Navi, Navigation
url: http://lambdax.cn
contact: ider[at]lambdax[dot]cn

logo: /images/logo.png
logo_dark: /images/logo-dark.png
logo_white: /images/logo-white.png

plugins:
- jekyll-seo-tag
- jekyll-sitemap

exclude:
- .gitignore
- .travis.yml
- LICENSE
- README.md
- CNAME
- Gemfile
- Gemfile.lock
- script
- vendor